---
- hosts: ubuntu
  become: yes
  tasks:
  - name: apache2 installation
    apt:
     name: apache2
     update_cache: yes
     state: present
  - name: apache2 start
    service:
      name: apache2
      state: started
      enabled: yes

  
