---
- hosts: node
  become: yes
  tasks:
  - name: install apache server
    package:
      name: "{{package_name}}"
      state: present
    notify:
    - restart apache
  - name: install php packages
    package:
      name: "{{php_packages}}"
      state: present
  - name: download web page
    get_url:
      url: https://raw.githubusercontent.com/happyshaiikh/php.info/master/info.php
      dest: /var/www/html/info.php
    notify:
    - restart apache
  handlers:
  - name: restart apache
    service:
      name: "{{package_name}}"
      state: restarted
